site_name: CeVIO AI User Guide (Unofficial Translation)
site_description: An unofficial CeVIO AI User Manual English translation.
repo_url: https://github.com/CeVIO-User-Guide-Unofficial/cevio-ai-en
repo_name: CUGU/CeVIO-AI

# Theme
theme:
  custom_dir: 'overrides'                  # This is where the customization of the theme lives
  name: material
  features:
    - announce.dismiss
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.footer
    - toc.follow
  icon:
    logo: fontawesome/solid/book
    favicon: images/c-solid.png
    repo: fontawesome/brands/github
  language: en
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: 中文（简体）
      link: https://zh.ceviodoc.uk
      lang: zh
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/CeVIO_st
      name: CeVIO on Twitter
    - icon: material/web
      link: https://cevio.jp/guide/cevio_ai/
      name: Original Japanese version of this User Manual 

# CSS
extra_css:
  - material/assets/stylesheets/extra.css
  - material/assets/stylesheets/footer.css

# Extensions
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys:
      key_map:
        mouse-wheel: "Mouse wheel"
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - toc:
      toc_depth: 6

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  # - offline
      # enabled: !ENV [OFFLINE, false]

# Contents
nav:
  - Home: 
    - index.md
    - intro/change-log.md
    - intro/change-log_website.md
    - intro/contact.md
    - intro/about.md
  - First Guide:
    - firstguide/system_requirements.md
    - firstguide/install.md
    - firstguide/install_cn_patch.md
  - Operation:
    - operation/index.md
    - operation/menu.md
    - operation/transport.md
    - operation/infopanel.md
    - operation/trackhead.md
    - operation/edittool.md
    - operation/adjusttool.md
  - Talk Track:
    - talktrack/tutorial_talk.md
    - talktrack/index.md
    - talktrack/talk_01.md
    - talktrack/longsentence.md
    - talktrack/talk_02.md
    - talktrack/talk_05.md
    - talktrack/phoneme.md
    - talktrack/phoneme_english.md
    - talktrack/talk_06.md
    - talktrack/talk_01_english.md
    - talktrack/phrasececlip.md
    - talktrack/search.md
    - talktrack/talk_04.md
  - Song Track:
    - songtrack/tutorial_song.md
    - songtrack/index.md
    - songtrack/songtrack.md
    - songtrack/song_02.md
    - songtrack/song_04.md
    - songtrack/song_04_english.md
    - songtrack/song_symbol.md
    - songtrack/song_03.md
    - songtrack/song_05.md
    - songtrack/song_07.md
    - songtrack/song_06.md
    - songtrack/fileimport.md
  - Audio Track:
    - audio/index.md
  - Options:
    - option/index.md
    - option/characterimage.md
  - Shortcut Key:
    - shortcutkey/index.md
  - External Interface:
    - interface/index.md
    - interface/com.md
    - interface/dotnet.md
  - FAQ and Bugs:
    - faq/index.md
    - faq/known_bugs.md
